In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

sns.set(style="whitegrid")
plt.rcParams["figure.figsize"] = (12, 6)

# Load CSV Files
csv1 = pd.read_csv(r"C:\Users\mbaki\Desktop\Proje\data\raw\23_24\23_24.csv")
csv2 = pd.read_csv(r"C:\Users\mbaki\Desktop\Proje\data\raw\23_24\23_24_teams_and_players.csv")
csv3 = pd.read_csv(r"C:\Users\mbaki\Desktop\Proje\data\raw\23_24\23_24_marketvalue_and_age.csv")

In [2]:
csv1

,Season,Week,Match Date,Home Team,Away Team,Home Goals,Away Goals,Home Performance,Away Performance,Home Formation,Away Formation,Home Players,Away Players
0,23/24,Round 38,24/05/24,Alanyaspor,Antalyaspor,1,1,7.03,6.78,4-2-3-1,4-2-3-1,Y. Karagöz; F. Hadergjonaj; F. Bayır; N. Lima;...,A. Dadakdeniz; M. Yilmaz; (c) V. Sarı; A. Gerx...
1,23/24,Round 38,25/05/24,Karagümrük,Samsunspor,3,1,7.01,6.74,4-2-3-1,4-2-3-1,E. Bilgin; N. Sangaré; (c) D. Biraschi; K. Gün...,J. Szumski; H. M. Tan; Y. E. Çift; Y. A. Benna...
2,23/24,Round 38,25/05/24,Sivasspor,Kayserispor,2,1,6.94,6.78,4-1-4-1,4-2-3-1,Đ. Nikolić; M. Paluli; A. Appindangoyé; M. Alb...,O. Piri; (c) J. Attamah; J. Jeanvier; A. Kocam...
3,23/24,Round 38,26/05/24,Adana DS,Başakşehir,2,6,6.35,7.20,5-4-1,4-1-4-1,Y. Aktaş; İ. Çokçalış; A. Gravillon; (c) D. To...,D. Dilmen; O. Kemen; H. Güreler; J. Opoku; L. ...
4,23/24,Round 38,26/05/24,Fenerbahçe,İstanbulspor,6,0,7.54,6.35,4-4-2,5-4-1,D. Livaković; B. Osayi-Samuel; R. Becão; Ç. Sö...,M. Serbest; D. Sambissa; B. Vardar; O. Erdoğan...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
374,23/24,Round 1,13/08/23,Sivasspor,Samsunspor,1,1,6.80,6.79,4-3-3,3-4-2-1,A. Ş. Vural; A. Okumuş; C. Osmanpaşa; S. Camar...,O. Kocuk; Z. Yavru; A. Öztürk; R. V. Drongelen...
375,23/24,Round 1,13/08/23,Adana DS,Rizespor,2,1,6.92,6.64,4-2-3-1,4-2-3-1,E. Özbir; J. Svensson; A. Gravillon; S. Güler;...,(c) G. Akkan; E. Korkmaz; H. Alikulov; E. Topç...
376,23/24,Round 1,13/08/23,Fenerbahçe,Gaziantep,2,1,7.03,6.42,4-1-4-1,4-2-3-1,A. Bayındır; B. Osayi-Samuel; R. Becão; A. Dji...,B. A. Şen; S. M'Bakata; A. Kızıldağ; (c) P. Dj...
377,23/24,Round 1,14/08/23,Alanyaspor,Başakşehir,2,0,7.19,6.61,4-3-3,4-1-4-1,E. Taşkıran; L. Augusto; F. Bayır; F. Aliti; Y...,M. Şengezer; Ş. Özbayraklı; E. Ié; L. Duarte; ...
378,23/24,Round 1,14/08/23,Karagümrük,Beşiktaş,0,1,6.65,7.10,4-3-3,4-3-3,M. Dituro; F. Veseli; R. Baniya; I. Drešević; ...,M. Günok; V. Rosier; (c) N. Uysal; O. Colley; ...

In [3]:
print(csv2)

    Season       Team Name            Player Name  Player Rating
0    23/24     Galatasaray          Dries Mertens           7.61
1    23/24      Fenerbahçe    Sebastian Szymański           7.55
2    23/24     Trabzonspor           Paul Onuachu           7.52
3    23/24     Galatasaray           Mauro Icardi           7.51
4    23/24       Sivasspor          Đorđe Nikolić           7.50
..     ...             ...                    ...            ...
628  23/24   Başakşehir FK      Yasin Yağız Dilek           0.00
629  23/24       Kasımpaşa        Hasan Yesilyurt           0.00
630  23/24  MKE Ankaragücü       Alperen Kuyubaşı           0.00
631  23/24    İstanbulspor  Muhammet Berkay Tekke           0.00
632  23/24       Konyaspor  Mehmet Ali Büyüksayar           0.00

[633 rows x 4 columns]

In [4]:
print(csv3)

          Team Name            Player Name  Age  Market Value
0       Galatasaray          Dries Mertens   37   1.80 mil. €
1        Fenerbahçe    Sebastian Szymański   25  17.00 mil. €
2       Trabzonspor           Paul Onuachu   30  11.00 mil. €
3       Galatasaray           Mauro Icardi   31  13.00 mil. €
4         Sivasspor          Đorđe Nikolić  NaN           NaN
..              ...                    ...  ...           ...
628   Başakşehir FK      Yasin Yağız Dilek   19      75 bin €
629       Kasımpaşa        Hasan Yesilyurt   32             -
630  MKE Ankaragücü       Alperen Kuyubaşı   24      25 bin €
631    İstanbulspor  Muhammet Berkay Tekke   21      25 bin €
632       Konyaspor  Mehmet Ali Büyüksayar   20     200 bin €

[633 rows x 4 columns]

In [5]:
# Detect rows containing '-'
mask = (csv3['Age'] == '-') | (csv3['Market Value'] == '-')

# Set 'Age' and 'Market Value' to NaN in these rows
csv3.loc[mask, ['Age', 'Market Value']] = np.nan

# Convert 'Age' column to numeric (NaN values are automatically preserved)
csv3['Age'] = pd.to_numeric(csv3['Age'], errors='coerce')

# Clean and convert 'Market Value' column to numeric
# First, convert expressions like 'mil. €' and 'bin €' to numerical values
def convert_market_value(value):
    if pd.isna(value):
        return np.nan
    value = value.replace(' mil. €', 'e6').replace(' bin €', 'e3').replace('€', '').replace('.', '').replace(',', '.')
    try:
        return float(value)
    except:
        return np.nan

csv3['Market Value'] = csv3['Market Value'].apply(convert_market_value)

# Check data types after cleaning
print("\nAfter Preprocessing:")
print(csv3.dtypes)

# Check the number of NaN values
print("\nNaN Values:")
print(csv3.isna().sum())

After Preprocessing:
Team Name        object
Player Name      object
Age             float64
Market Value    float64
dtype: object

NaN Values:
Team Name        0
Player Name      0
Age             43
Market Value    43
dtype: int64

In [6]:
print(csv3)

          Team Name            Player Name   Age  Market Value
0       Galatasaray          Dries Mertens  37.0  1.800000e+08
1        Fenerbahçe    Sebastian Szymański  25.0  1.700000e+09
2       Trabzonspor           Paul Onuachu  30.0  1.100000e+09
3       Galatasaray           Mauro Icardi  31.0  1.300000e+09
4         Sivasspor          Đorđe Nikolić   NaN           NaN
..              ...                    ...   ...           ...
628   Başakşehir FK      Yasin Yağız Dilek  19.0  7.500000e+04
629       Kasımpaşa        Hasan Yesilyurt   NaN           NaN
630  MKE Ankaragücü       Alperen Kuyubaşı  24.0  2.500000e+04
631    İstanbulspor  Muhammet Berkay Tekke  21.0  2.500000e+04
632       Konyaspor  Mehmet Ali Büyüksayar  20.0  2.000000e+05

[633 rows x 4 columns]

In [7]:
# Merge two CSV files
merged_csv2_csv3 = pd.merge(csv2, csv3, on=['Team Name', 'Player Name'], how='left')

# Check the merged data
print(merged_csv2_csv3.head())

  Season    Team Name          Player Name  Player Rating   Age  Market Value
0  23/24  Galatasaray        Dries Mertens           7.61  37.0  1.800000e+08
1  23/24   Fenerbahçe  Sebastian Szymański           7.55  25.0  1.700000e+09
2  23/24  Trabzonspor         Paul Onuachu           7.52  30.0  1.100000e+09
3  23/24  Galatasaray         Mauro Icardi           7.51  31.0  1.300000e+09
4  23/24    Sivasspor        Đorđe Nikolić           7.50   NaN           NaN

In [8]:
# Fill NaN values with team-wise averages
merged_csv2_csv3['Age'] = merged_csv2_csv3.groupby('Team Name')['Age'].transform(lambda x: x.fillna(x.mean()))
merged_csv2_csv3['Market Value'] = merged_csv2_csv3.groupby('Team Name')['Market Value'].transform(lambda x: x.fillna(x.mean()))

# Verify the results
print(merged_csv2_csv3.head())

  Season    Team Name          Player Name  Player Rating        Age  \
0  23/24  Galatasaray        Dries Mertens           7.61  37.000000
1  23/24   Fenerbahçe  Sebastian Szymański           7.55  25.000000
2  23/24  Trabzonspor         Paul Onuachu           7.52  30.000000
3  23/24  Galatasaray         Mauro Icardi           7.51  31.000000
4  23/24    Sivasspor        Đorđe Nikolić           7.50  30.142857

   Market Value
0  1.800000e+08
1  1.700000e+09
2  1.100000e+09
3  1.300000e+09
4  3.501786e+07

In [9]:
def extract_surname(full_name):
    name = full_name.replace('(c)', '').strip()
    parts = name.split(' ')
    return parts[-1] if parts else name

# Function to modify team names
def modify_team_name(team_name):
    team_name_lower = team_name.lower()
    if team_name_lower == 'karagümrük':
        return 'fati'
    elif team_name_lower == 'mke ankaragücü':
        return 'anka'
    elif team_name_lower == 'çaykur rizespor':
        return 'rize'
    else:
        return team_name_lower[:4]

In [10]:
# Split player names into lists
csv1['Home Players'] = csv1['Home Players'].str.split('; ')
csv1['Away Players'] = csv1['Away Players'].str.split('; ')

# Extract surnames for Home and Away players
csv1['Home Players'] = csv1['Home Players'].apply(lambda players: [extract_surname(player) for player in players])
csv1['Away Players'] = csv1['Away Players'].apply(lambda players: [extract_surname(player) for player in players])

MAX_PLAYER = 11

# Split player lists into separate columns
def split_players(player_list, prefix):
    df = player_list.apply(lambda players: pd.Series(players[:MAX_PLAYER]))
    df = df.rename(columns=lambda x: f'{prefix} Player {x + 1}')
    return df

home_players_df = split_players(csv1['Home Players'], 'Home')
away_players_df = split_players(csv1['Away Players'], 'Away')

# Remove original player columns and add new separated columns
csv1 = csv1.drop(['Home Players', 'Away Players'], axis=1)
csv1 = pd.concat([csv1, home_players_df, away_players_df], axis=1)

# Modify Home and Away Team names
csv1['Home Team'] = csv1['Home Team'].apply(modify_team_name).str.strip()
csv1['Away Team'] = csv1['Away Team'].apply(modify_team_name).str.strip()

In [11]:
# Clean csv2 dataset
merged_csv2_csv3['Player Name'] = csv2['Player Name'].apply(extract_surname).str.lower().str.strip()
merged_csv2_csv3['Team Name'] = csv2['Team Name'].apply(modify_team_name).str.strip()
player_rating_dict = merged_csv2_csv3.set_index('Player Name')['Player Rating'].to_dict()

In [12]:
print(merged_csv2_csv3)

    Season Team Name Player Name  Player Rating        Age  Market Value
0    23/24      gala     mertens           7.61  37.000000  1.800000e+08
1    23/24      fene   szymański           7.55  25.000000  1.700000e+09
2    23/24      trab     onuachu           7.52  30.000000  1.100000e+09
3    23/24      gala      icardi           7.51  31.000000  1.300000e+09
4    23/24      siva     nikolić           7.50  30.142857  3.501786e+07
..     ...       ...         ...            ...        ...           ...
628  23/24      başa       dilek           0.00  19.000000  7.500000e+04
629  23/24      kası   yesilyurt           0.00  26.518519  5.435556e+07
630  23/24      anka    kuyubaşı           0.00  24.000000  2.500000e+04
631  23/24      i̇st       tekke           0.00  21.000000  2.500000e+04
632  23/24      kony  büyüksayar           0.00  20.000000  2.000000e+05

[633 rows x 6 columns]

In [13]:
# Combine Team and Player names in merged_csv2_csv3 and convert to lowercase
merged_csv2_csv3['Team Name'] = merged_csv2_csv3['Team Name'].str.lower().str.strip()
merged_csv2_csv3['Player Name'] = merged_csv2_csv3['Player Name'].str.lower().str.strip()

merged_csv2_csv3['Team_Player'] = merged_csv2_csv3['Team Name'] + '_' + merged_csv2_csv3['Player Name']

print(merged_csv2_csv3)

    Season Team Name Player Name  Player Rating        Age  Market Value  \
0    23/24      gala     mertens           7.61  37.000000  1.800000e+08
1    23/24      fene   szymański           7.55  25.000000  1.700000e+09
2    23/24      trab     onuachu           7.52  30.000000  1.100000e+09
3    23/24      gala      icardi           7.51  31.000000  1.300000e+09
4    23/24      siva     nikolić           7.50  30.142857  3.501786e+07
..     ...       ...         ...            ...        ...           ...
628  23/24      başa       dilek           0.00  19.000000  7.500000e+04
629  23/24      kası   yesilyurt           0.00  26.518519  5.435556e+07
630  23/24      anka    kuyubaşı           0.00  24.000000  2.500000e+04
631  23/24      i̇st       tekke           0.00  21.000000  2.500000e+04
632  23/24      kony  büyüksayar           0.00  20.000000  2.000000e+05

         Team_Player
0       gala_mertens
1     fene_szymański
2       trab_onuachu
3        gala_icardi
4       siva_nikolić
..               ...
628       başa_dilek
629   kası_yesilyurt
630    anka_kuyubaşı
631       i̇st_tekke
632  kony_büyüksayar

[633 rows x 7 columns]

In [14]:
# Function to concatenate team and player names in lowercase
def concatenate_team_player_lower(team_column, player_column):
    return team_column.str.lower().str.strip() + '_' + player_column.str.lower().str.strip()

# Concatenate Home Players
for i in range(1, MAX_PLAYER + 1):
    home_player_col = f'Home Player {i}'
    new_col = f'Home_Player_{i}_TeamPlayer'
    csv1[new_col] = concatenate_team_player_lower(csv1['Home Team'], csv1[home_player_col])

# Concatenate Away Players
for i in range(1, MAX_PLAYER + 1):
    away_player_col = f'Away Player {i}'
    new_col = f'Away_Player_{i}_TeamPlayer'
    csv1[new_col] = concatenate_team_player_lower(csv1['Away Team'], csv1[away_player_col])

# Remove original player columns after concatenation
home_player_team_cols = [f'Home Player {i}' for i in range(1, MAX_PLAYER + 1)]
away_player_team_cols = [f'Away Player {i}' for i in range(1, MAX_PLAYER + 1)]

# Collect all Team_Player columns
team_player_cols = home_player_team_cols + away_player_team_cols

# Drop existing Team_Player columns if they exist
existing_team_player_cols = [col for col in team_player_cols if col in csv1.columns]
csv1 = csv1.drop(existing_team_player_cols, axis=1)

print(csv1)

    Season      Week Match Date Home Team Away Team  Home Goals  Away Goals  \
0    23/24  Round 38   24/05/24      alan      anta           1           1
1    23/24  Round 38   25/05/24      fati      sams           3           1
2    23/24  Round 38   25/05/24      siva      kays           2           1
3    23/24  Round 38   26/05/24      adan      başa           2           6
4    23/24  Round 38   26/05/24      fene      i̇st           6           0
..     ...       ...        ...       ...       ...         ...         ...
374  23/24   Round 1   13/08/23      siva      sams           1           1
375  23/24   Round 1   13/08/23      adan      rize           2           1
376  23/24   Round 1   13/08/23      fene      gazi           2           1
377  23/24   Round 1   14/08/23      alan      başa           2           0
378  23/24   Round 1   14/08/23      fati      beşi           0           1

     Home Performance  Away Performance Home Formation  ...  \
0                7.03              6.78        4-2-3-1  ...
1                7.01              6.74        4-2-3-1  ...
2                6.94              6.78        4-1-4-1  ...
3                6.35              7.20          5-4-1  ...
4                7.54              6.35          4-4-2  ...
..                ...               ...            ...  ...
374              6.80              6.79          4-3-3  ...
375              6.92              6.64        4-2-3-1  ...
376              7.03              6.42        4-1-4-1  ...
377              7.19              6.61          4-3-3  ...
378              6.65              7.10          4-3-3  ...

    Away_Player_2_TeamPlayer Away_Player_3_TeamPlayer  \
0                anta_yilmaz                anta_sarı
1                   sams_tan                sams_çift
2               kays_attamah            kays_jeanvier
3                 başa_kemen             başa_güreler
4              i̇st_sambissa              i̇st_vardar
..                       ...                      ...
374               sams_yavru              sams_öztürk
375             rize_korkmaz            rize_alikulov
376            gazi_m'bakata            gazi_kızıldağ
377          başa_özbayraklı                  başa_ié
378              beşi_rosier               beşi_uysal

    Away_Player_4_TeamPlayer Away_Player_5_TeamPlayer  \
0             anta_gerxhaliu               anta_vural
1             sams_bennasser                sams_bola
2               kays_kocaman              kays_carole
3                 başa_opoku              başa_dubois
4               i̇st_erdoğan                i̇st_coly
..                       ...                      ...
374           sams_drongelen           sams_schindler
375               rize_topçu            rize_pehlivan
376          gazi_djilobodji              gazi_khacef
377              başa_duarte               başa_touba
378              beşi_colley             beşi_masuaku

    Away_Player_6_TeamPlayer Away_Player_7_TeamPlayer  \
0            anta_kałuziński           anta_milošević
1                 sams_çelik                sams_tait
2                kays_yılmaz            kays_bourabia
3                 başa_ergün               başa_türüç
4                 i̇st_yaşar               i̇st_temel
..                       ...                      ...
374           sams_antalyalı              sams_ntcham
375            rize_olawoyin                rize_pala
376            gazi_jevtović              gazi_soyalp
377              başa_karzev              başa_gürler
378                beşi_uçan      beşi_hadžiahmetović

    Away_Player_8_TeamPlayer Away_Player_9_TeamPlayer  \
0                anta_streek              anta_safuri
1                 sams_raman               sams_holse
2                  kays_mané               kays_özbek
3               başa_şahiner               başa_özcan
4            i̇st_vorobjovas             i̇st_jackson
..                       ...                      ...
374                sams_bola              sams_kılınç
375              rize_zeqiri              rize_pinchi
376          gazi_eskihellaç               gazi_maxim
377             başa_şahiner              başa_pelkas
378           beşi_fernandes               beşi_bulut

    Away_Player_10_TeamPlayer Away_Player_11_TeamPlayer
0                anta_larsson                anta_buksa
1                   sams_muja                 sams_kara
2                  kays_morte              kays_bahoken
3               başa_davidson               başa_piątek
4                  i̇st_şahan              i̇st_mamadou
..                        ...                       ...
374               sams_fofana        sams_mouandilmadji
375                rize_keser                rize_diouf
376               gazi_gradel             gazi_marković
377           başa_figueiredo               başa_piątek
378            beşi_aboubakar               beşi_muleka

[379 rows x 33 columns]

In [15]:
# -------------------------------------------------------------
# 1) Select necessary columns from merged_csv2_csv3
#    based on Team_Player for Age, Market Value, Rating
# -------------------------------------------------------------
df2_subset = merged_csv2_csv3[['Team_Player', 'Age', 'Market Value', 'Player Rating']].copy()

# -------------------------------------------------------------
# 2) Get list of Home_Player_i_TeamPlayer and Away_Player_i_TeamPlayer columns
# -------------------------------------------------------------
home_teamplayer_cols = [f'Home_Player_{i}_TeamPlayer' for i in range(1, MAX_PLAYER + 1)]
away_teamplayer_cols = [f'Away_Player_{i}_TeamPlayer' for i in range(1, MAX_PLAYER + 1)]
player_teamplayer_cols = home_teamplayer_cols + away_teamplayer_cols

# -------------------------------------------------------------
# 3) Loop through each TeamPlayer column to merge Age, Market Value, Rating
#    into csv1
# -------------------------------------------------------------
for col in player_teamplayer_cols:
    # Step 3a: Merge based on Team_Player
    csv1 = pd.merge(
        csv1,
        df2_subset,
        how="left",
        left_on=col,     # csv1's Home_Player_i_TeamPlayer or Away_Player_i_TeamPlayer
        right_on="Team_Player",
        suffixes=("", f"_{col}")  # Add suffix to avoid column name conflicts
    )

    # Step 3b: Rename the merged columns appropriately
    csv1.rename(
        columns={
            'Age': f"{col}_Age",
            'Market Value': f"{col}_MarketValue",
            'Player Rating': f"{col}_Rating"
        },
        inplace=True
    )

    # Step 3c: Drop the Team_Player column after merging
    if "Team_Player" in csv1.columns:
        csv1.drop(columns="Team_Player", inplace=True)

# -------------------------------------------------------------
# 4) Verify the added columns in csv1
# -------------------------------------------------------------
print("Age, Market Value, and Player Rating columns added to csv1:\n")
print(csv1.head())

Age, Market Value, and Player Rating columns added to csv1:

  Season      Week Match Date Home Team Away Team  Home Goals  Away Goals  \
0  23/24  Round 38   24/05/24      alan      anta           1           1
1  23/24  Round 38   25/05/24      fati      sams           3           1
2  23/24  Round 38   25/05/24      siva      kays           2           1
3  23/24  Round 38   26/05/24      adan      başa           2           6
4  23/24  Round 38   26/05/24      fene      i̇st           6           0

   Home Performance  Away Performance Home Formation  ...  \
0              7.03              6.78        4-2-3-1  ...
1              7.01              6.74        4-2-3-1  ...
2              6.94              6.78        4-1-4-1  ...
3              6.35              7.20          5-4-1  ...
4              7.54              6.35          4-4-2  ...

  Away_Player_8_TeamPlayer_Rating Away_Player_9_TeamPlayer_Age  \
0                            6.68                         29.0
1                            6.67                         25.0
2                            6.80                         21.0
3                            6.89                         26.0
4                            6.68                         23.0

  Away_Player_9_TeamPlayer_MarketValue Away_Player_9_TeamPlayer_Rating  \
0                         1.300000e+08                            7.04
1                         3.400000e+08                            6.90
2                         3.500000e+05                            6.60
3                         2.700000e+08                            6.84
4                         5.500000e+09                            6.77

  Away_Player_10_TeamPlayer_Age Away_Player_10_TeamPlayer_MarketValue  \
0                          31.0                           150000000.0
1                          26.0                           370000000.0
2                          31.0                           150000000.0
3                          33.0                              750000.0
4                          25.0                              275000.0

  Away_Player_10_TeamPlayer_Rating Away_Player_11_TeamPlayer_Age  \
0                             6.97                          28.0
1                             6.78                          28.0
2                             6.80                          32.0
3                             7.11                          29.0
4                             6.67                          26.0

  Away_Player_11_TeamPlayer_MarketValue Away_Player_11_TeamPlayer_Rating
0                           600000000.0                             7.19
1                           120000000.0                             6.75
2                              800000.0                             6.74
3                           650000000.0                             7.20
4                              400000.0                             6.69

[5 rows x 99 columns]

In [16]:
csv1

,Season,Week,Match Date,Home Team,Away Team,Home Goals,Away Goals,Home Performance,Away Performance,Home Formation,...,Away_Player_8_TeamPlayer_Rating,Away_Player_9_TeamPlayer_Age,Away_Player_9_TeamPlayer_MarketValue,Away_Player_9_TeamPlayer_Rating,Away_Player_10_TeamPlayer_Age,Away_Player_10_TeamPlayer_MarketValue,Away_Player_10_TeamPlayer_Rating,Away_Player_11_TeamPlayer_Age,Away_Player_11_TeamPlayer_MarketValue,Away_Player_11_TeamPlayer_Rating
0,23/24,Round 38,24/05/24,alan,anta,1,1,7.03,6.78,4-2-3-1,...,6.68,29.0,1.300000e+08,7.04,31.0,150000000.0,6.97,28.0,6.000000e+08,7.19
1,23/24,Round 38,25/05/24,fati,sams,3,1,7.01,6.74,4-2-3-1,...,6.67,25.0,3.400000e+08,6.90,26.0,370000000.0,6.78,28.0,1.200000e+08,6.75
2,23/24,Round 38,25/05/24,siva,kays,2,1,6.94,6.78,4-1-4-1,...,6.80,21.0,3.500000e+05,6.60,31.0,150000000.0,6.80,32.0,8.000000e+05,6.74
3,23/24,Round 38,26/05/24,adan,başa,2,6,6.35,7.20,5-4-1,...,6.89,26.0,2.700000e+08,6.84,33.0,750000.0,7.11,29.0,6.500000e+08,7.20
4,23/24,Round 38,26/05/24,fene,i̇st,6,0,7.54,6.35,4-4-2,...,6.68,23.0,5.500000e+09,6.77,25.0,275000.0,6.67,26.0,4.000000e+05,6.69
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
374,23/24,Round 1,13/08/23,siva,sams,1,1,6.80,6.79,4-3-3,...,6.75,30.0,1.700000e+08,7.12,33.0,250000.0,6.82,26.0,2.900000e+08,6.88
375,23/24,Round 1,13/08/23,adan,rize,2,1,6.92,6.64,4-2-3-1,...,6.88,28.0,5.000000e+05,6.56,28.0,750000.0,6.87,26.0,9.189569e+07,6.30
376,23/24,Round 1,13/08/23,fene,gazi,2,1,7.03,6.42,4-1-4-1,...,6.93,34.0,7.000000e+05,7.16,37.0,650000.0,6.73,30.0,1.500000e+08,6.82
377,23/24,Round 1,14/08/23,alan,başa,2,0,7.19,6.61,4-3-3,...,6.89,31.0,1.800000e+08,7.04,28.0,230000000.0,6.88,29.0,6.500000e+08,7.20
378,23/24,Round 1,14/08/23,fati,beşi,0,1,6.65,7.10,4-3-3,...,7.19,30.0,1.400000e+08,6.76,32.0,200000000.0,6.78,25.0,3.500000e+08,6.90

In [17]:
home_teamplayer_cols = [f'Home_Player_{i}_TeamPlayer' for i in range(1, MAX_PLAYER + 1)]
away_teamplayer_cols = [f'Away_Player_{i}_TeamPlayer' for i in range(1, MAX_PLAYER + 1)]
player_teamplayer_cols = home_teamplayer_cols + away_teamplayer_cols

In [18]:
# Drop Team_Player columns after merging
csv1.drop(columns=player_teamplayer_cols, inplace=True)

# -------------------------------------------------------------
# 5) Save the processed csv1 to the desired directory
# -------------------------------------------------------------
save_path = r"C:\Users\mbaki\Desktop\Proje\data\processed\all_season\23_24_processed.csv"
csv1.to_csv(save_path, index=False)

In [19]:
print(csv1.columns)

Index(['Season', 'Week', 'Match Date', 'Home Team', 'Away Team', 'Home Goals',
       'Away Goals', 'Home Performance', 'Away Performance', 'Home Formation',
       'Away Formation', 'Home_Player_1_TeamPlayer_Age',
       'Home_Player_1_TeamPlayer_MarketValue',
       'Home_Player_1_TeamPlayer_Rating', 'Home_Player_2_TeamPlayer_Age',
       'Home_Player_2_TeamPlayer_MarketValue',
       'Home_Player_2_TeamPlayer_Rating', 'Home_Player_3_TeamPlayer_Age',
       'Home_Player_3_TeamPlayer_MarketValue',
       'Home_Player_3_TeamPlayer_Rating', 'Home_Player_4_TeamPlayer_Age',
       'Home_Player_4_TeamPlayer_MarketValue',
       'Home_Player_4_TeamPlayer_Rating', 'Home_Player_5_TeamPlayer_Age',
       'Home_Player_5_TeamPlayer_MarketValue',
       'Home_Player_5_TeamPlayer_Rating', 'Home_Player_6_TeamPlayer_Age',
       'Home_Player_6_TeamPlayer_MarketValue',
       'Home_Player_6_TeamPlayer_Rating', 'Home_Player_7_TeamPlayer_Age',
       'Home_Player_7_TeamPlayer_MarketValue',
       'Home_Player_7_TeamPlayer_Rating', 'Home_Player_8_TeamPlayer_Age',
       'Home_Player_8_TeamPlayer_MarketValue',
       'Home_Player_8_TeamPlayer_Rating', 'Home_Player_9_TeamPlayer_Age',
       'Home_Player_9_TeamPlayer_MarketValue',
       'Home_Player_9_TeamPlayer_Rating', 'Home_Player_10_TeamPlayer_Age',
       'Home_Player_10_TeamPlayer_MarketValue',
       'Home_Player_10_TeamPlayer_Rating', 'Home_Player_11_TeamPlayer_Age',
       'Home_Player_11_TeamPlayer_MarketValue',
       'Home_Player_11_TeamPlayer_Rating', 'Away_Player_1_TeamPlayer_Age',
       'Away_Player_1_TeamPlayer_MarketValue',
       'Away_Player_1_TeamPlayer_Rating', 'Away_Player_2_TeamPlayer_Age',
       'Away_Player_2_TeamPlayer_MarketValue',
       'Away_Player_2_TeamPlayer_Rating', 'Away_Player_3_TeamPlayer_Age',
       'Away_Player_3_TeamPlayer_MarketValue',
       'Away_Player_3_TeamPlayer_Rating', 'Away_Player_4_TeamPlayer_Age',
       'Away_Player_4_TeamPlayer_MarketValue',
       'Away_Player_4_TeamPlayer_Rating', 'Away_Player_5_TeamPlayer_Age',
       'Away_Player_5_TeamPlayer_MarketValue',
       'Away_Player_5_TeamPlayer_Rating', 'Away_Player_6_TeamPlayer_Age',
       'Away_Player_6_TeamPlayer_MarketValue',
       'Away_Player_6_TeamPlayer_Rating', 'Away_Player_7_TeamPlayer_Age',
       'Away_Player_7_TeamPlayer_MarketValue',
       'Away_Player_7_TeamPlayer_Rating', 'Away_Player_8_TeamPlayer_Age',
       'Away_Player_8_TeamPlayer_MarketValue',
       'Away_Player_8_TeamPlayer_Rating', 'Away_Player_9_TeamPlayer_Age',
       'Away_Player_9_TeamPlayer_MarketValue',
       'Away_Player_9_TeamPlayer_Rating', 'Away_Player_10_TeamPlayer_Age',
       'Away_Player_10_TeamPlayer_MarketValue',
       'Away_Player_10_TeamPlayer_Rating', 'Away_Player_11_TeamPlayer_Age',
       'Away_Player_11_TeamPlayer_MarketValue',
       'Away_Player_11_TeamPlayer_Rating'],
      dtype='object')